---
- name: common ansible play book
  hosts: all
  become: yes
  tasks:
    # apt
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
    # python3-pip
    - name: install Python3
      apt:
        name: python3-pip
        state: latest
        update_cache: yes
    - name: Install PIP
      apt: name="{{ 'python-pip' if ansible_distribution_version in ['14.04', '18.04'] else 'python3-pip' }}"