---
- name: node ansible play book
  hosts: all
  become: yes
#  pre_tasks:
#    - include_vars: "../../env_vars/vars.yml"
  tasks:
    - name: Debian nodejs install
      apt:
        name: nodejs
        state: present

    # npm cli
    - name: npm cli global install
      shell: "npm i -g @vue/cli"
